// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr8k7oZbT042ZM0_R8MLOQBHTkhl2ohmM',
    appId: '1:406099696497:web:87e25e51afe982cd3574d0',
    messagingSenderId: '667718287960',
    projectId: 'huaweidigi2',
    authDomain: 'flutterfire-e2e-tests.firebaseapp.com',
    databaseURL:
        'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfire-e2e-tests.appspot.com',
    measurementId: 'G-JN95N1JV2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    /*
    apiKey: 'AIzaSyAG5P5oVZqGvyo8ardhSw-ewVk79qvRubs',//'AIzaSyCUu_1wuDLij35CTM8H43i3QrxvXJ-WPm8',
    appId: '1:48682990645:android:22334153ea11942ffc057c',//'1:694859108332:android:832669d06d602e29417ac9',
    messagingSenderId: '48682990645',//'694859108332',
    projectId: 'flutter-firebase-messagi-f5034',//'cateringservice-fcm',
    databaseURL:
        'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-messagi-f5034.appspot.com'//'cateringservice-fcm.appspot.com',

     */


      apiKey: 'AIzaSyBr8k7oZbT042ZM0_R8MLOQBHTkhl2ohmM',
      appId: '1:667718287960:android:ba4ee300d4cd65c84c802d',
      messagingSenderId: '667718287960',
      projectId: 'huaweidigi2',
      //databaseURL:
      //'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
      storageBucket: 'huaweidigi2.appspot.com',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1zpgmngtRmkBZXQmL-gC2X_ZE3bVstI',
    appId: '1:667718287960:ios:44918d7b9814521d4c802d',
    messagingSenderId: '667718287960',
    projectId: 'huaweidigi2',
    //databaseURL:
    //    'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'huaweidigi2.appspot.com',
    //androidClientId:
    //    '406099696497-17qn06u8a0dc717u8ul7s49ampk13lul.apps.googleusercontent.com',
    //iosClientId:
    //    '694859108332-j97tgehos7s5q2e2cepm4m1e97sp9fr5.apps.googleusercontent.com',
    iosBundleId: 'com.huaweidigi.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUu_1wuDLij35CTM8H43i3QrxvXJ-WPm8',//'AIzaSyDooSUGSf63Ghq02_iIhtnmwMDs4HlWS6c',
    appId: '1:694859108332:android:832669d06d602e29417ac9',
    messagingSenderId: '694859108332',
    projectId: 'cateringservice-fcm',
    databaseURL:
        'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfire-e2e-tests.appspot.com',
    androidClientId:
        '406099696497-17qn06u8a0dc717u8ul7s49ampk13lul.apps.googleusercontent.com',
    iosClientId:
        '406099696497-irb7edfevfkhi6t5s9kbuq1mt1og95rg.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.messaging',
  );
}
